name: yuque
description: YuQue built with Flutter.

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_asset_generator: ^0.4.4
  flutter_spinkit: 4.1.2
  http: ^0.12.0+4
  oktoast: 2.3.1
  provider: 4.0.2

dependency_overrides:
  crypto: 2.1.4
  dartx: ^0.3.0
  image: 2.1.12
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/